# hash:sha256:1358ae631cea9e003084cc9c733c5879b67872978be4e594a41dba1219af31d9
FROM registry.codeocean.com/codeocean/miniconda3:4.9.2-cuda11.7.0-cudnn8-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive

# Update and install necessary packages
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        wget \
        gzip=1.10-0ubuntu4.1 \
        libcudnn8=8.6.0.163-1+cuda11.8 \
        libxext6=2:1.3.4-0ubuntu1 \
        libxrender1=1:0.9.10-1 \
        graphviz \
        libgraphviz-dev \
        pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Install CUDA 12.2
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin \
    && mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600 \
    && wget https://developer.download.nvidia.com/compute/cuda/12.2.2/local_installers/cuda-repo-ubuntu2004-12-2-local_12.2.2-535.104.05-1_amd64.deb \
    && dpkg -i cuda-repo-ubuntu2004-12-2-local_12.2.2-535.104.05-1_amd64.deb \
    && cp /var/cuda-repo-ubuntu2004-12-2-local/cuda-*-keyring.gpg /usr/share/keyrings/ \
    && apt-get update \
    && apt-get -y install cuda

# Install conda packages
RUN conda install -y \
        conda==23.7.4 \
        jupyter==1.0.0 \
        networkx==3.1 \
        python==3.10.4 \
        pygraphviz \
    && conda clean -ya

# Install pip packages
RUN pip install -U --no-cache-dir \
    gputil \
    ipython \
    graphviz==0.20.1 \
    ipython \
    matplotlib==3.7.1 \
    multiprocess==0.70.15 \
    pandas==2.0.1 \
    psutil==5.9.5 \
    pydot==1.4.2 \
    rdkit==2022.3.5 \
    tabulate \
    deepchem \
    tensorflow==2.12.0 \
    jinja2==2.11.3 \
    nbconvert==6.1.0 \
    markupsafe \
    tqdm==4.66.1